services:
  new-service: # <-- EDIT ME
    image: <SERVICE-IMAGE>:${SERVICE_VERSION} # ! <-- FILL IMAGE (+ ADD BUILD IF NEEDED)
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    user: ${USER_ID}:${GROUP_ID}
    security_opt:
      - no-new-privileges=true
    read_only: true
    cap_drop:
      - ALL

    environment:
      # ...
      TZ: ${TZ}

    # secrets:
    #   - service-secret

    # volumes:
    #   - .docker/data:/ ...

    networks:
      # - service-net
      # - socket-proxy-net
      - traefik-net

    healthcheck:
      test: ["CMD", " ... "] # <-- FILL HERE
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

    # # limit resources
    # cpus: 0.5
    # mem_limit: 256m
    # pids_limit: 10

    # # logging
    # logging:
    #   driver: json-file
    #   options:
    #     max-size: 10m
    #     max-file: 3

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NET}" # declare or force network for traefik docker provider
      - "traefik.http.routers.${CONTAINER_NAME}-https.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.${CONTAINER_NAME}-https.entrypoints=websecure"
      - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=${TRAEFIK_PORT}"

networks:
  # service-net: # specific network name for this service
  #   external: true
  #   name: ${SERVICE_NET}
  # socket-proxy-net:
  #   external: true
  #   name: ${SOCKET_PROXY_NET}
  traefik-net: # public traefik network
    external: true
    name: ${TRAEFIK_NET}

# secrets:
#   service-secret:
#     file: .docker/.secrets/service-secret
